const URL="https://jlmqnvyznyaoapjkyjmj.supabase.co",KEY="sb_publishable_gKNmo1rAdNZfg_BWGCehxQ_qfaoD3nj",sb=supabase.createClient(URL,KEY);
let user=null,state=null,chan=null,timer=null,remote=false;
const $=x=>document.getElementById(x),num=(v,d=0)=>{v=+v||0;let p=10**d;return Math.round(v*p)/p},iso=()=>new Date().toISOString().slice(0,10),clone=x=>JSON.parse(JSON.stringify(x));
const dparse=s=>new Date(s+"T00:00:00"),add=(s,n)=>{let d=dparse(s);d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)},days=(a,b)=>Math.round((dparse(b)-dparse(a))/86400000);
function status(t,c=""){let e=$("sync");e.textContent=t;e.className="pill "+c}
async function seed(){let {data,error}=await sb.from("app_seed").select("content").order("part");if(error)throw error;let b=(data||[]).map(x=>x.content).join(""),bin=Uint8Array.from(atob(b),c=>c.charCodeAt(0)),stream=new Blob([bin]).stream().pipeThrough(new DecompressionStream("gzip"));return JSON.parse(await new Response(stream).text())}
function mergeSeed(s,base){let have=new Set((s.foods||[]).map(f=>f.name));return {...base,...s,foods:[...(s.foods||[]),...(base.foods||[]).filter(f=>!have.has(f.name))]}}
async function loadCloud(){
 let {data,error}=await sb.from("app_state").select("state").eq("user_id",user.id).maybeSingle(); if(error)throw error;
 let base=await seed();
 if(data?.state) state=mergeSeed(data.state,base); else {state=base; await sb.from("app_state").insert({user_id:user.id,state})}
 if(!state.selectedDate)state.selectedDate=iso(); renderAll(); $("auth").classList.add("hidden"); $("signout").classList.remove("hidden"); status("Live","live");
 if(chan)await sb.removeChannel(chan);
 chan=sb.channel("cut-"+user.id).on("postgres_changes",{event:"UPDATE",schema:"public",table:"app_state",filter:`user_id=eq.${user.id}`},p=>{
   if(remote||!p.new?.state)return; let incoming=mergeSeed(p.new.state,base); if(JSON.stringify(incoming)===JSON.stringify(state))return;
   remote=true;state=incoming;renderAll();remote=false;status("Updated","live");setTimeout(()=>status("Live","live"),800);
 }).subscribe();
}
function save(){if(!user||remote)return;clearTimeout(timer);status("Syncing…");timer=setTimeout(async()=>{let {error}=await sb.from("app_state").upsert({user_id:user.id,state,updated_at:new Date().toISOString()},{onConflict:"user_id"});status(error?"Sync error":"Live",error?"":"live")},300)}
async function boot(){let {data:{session}}=await sb.auth.getSession();if(session?.user){user=session.user;await loadCloud()}else status("Sign in");
 sb.auth.onAuthStateChange(async(e,s)=>{if(e==="SIGNED_IN"&&s?.user&&s.user.id!==user?.id){user=s.user;await loadCloud()}if(e==="SIGNED_OUT"){user=null;$("auth").classList.remove("hidden");$("signout").classList.add("hidden");status("Signed out")}})}
$("signin").onclick=async()=>{let {error}=await sb.auth.signInWithPassword({email:$("email").value.trim(),password:$("pass").value});$("amsg").textContent=error?error.message:"Signed in…";$("amsg").className="notice "+(error?"danger":"")};
$("signup").onclick=async()=>{let e=$("email").value.trim(),p=$("pass").value;if(!e||p.length<6){$("amsg").textContent="Use a valid email and password of at least 6 characters.";return}let {data,error}=await sb.auth.signUp({email:e,password:p,options:{emailRedirectTo:location.href}});$("amsg").textContent=error?error.message:(data.session?"Account created. Loading…":"Account created. Check your email once to confirm it, then sign in.");$("amsg").className="notice "+(error?"danger":"")};
$("signout").onclick=()=>sb.auth.signOut();
function weight(date=iso()){let a=Object.entries(state.weights||{}).filter(([d,v])=>d<=date&&v?.weight).sort();return a.length?+a.at(-1)[1].weight:+state.settings.startWeight}
function target(){
 let s=state.settings,w=weight(),bf=Math.max(0,Math.min(.7,+s.bodyFat||.22)),lean=w*(1-bf),k=370+21.6*lean,m=s.sex==="Female"?10*w+6.25*s.heightCm-5*s.age-161:10*w+6.25*s.heightCm-5*s.age+5,bmr=(k+m)/2;
 let maint=s.manualMaintenance?+s.manualMaintenance:s.maintenanceAtStart*Math.pow(w/s.startWeight,.75),rem=Math.max(0,days(iso(),s.goalDate)),lose=Math.max(0,w-s.goalWeight),raw=rem?maint-lose*7700/rem:maint,cal=Math.max(bmr,raw),def=Math.max(0,maint-cal),pro=w*2.2*.9,fat=w*2.2*.4,carb=Math.max(0,(cal-pro*4-fat*9)/4),dl=def/7700,pd=dl&&lose?add(iso(),Math.ceil(lose/dl)):s.goalDate;
 let st=w<=s.goalWeight?"GOAL REACHED":rem<=0?"CHOOSE A FUTURE DATE":raw<bmr?"DATE TOO AGGRESSIVE — BMR FLOOR USED":"ON TRACK FOR SELECTED DATE";return{w,bmr,maint,cal,def,pro,fat,carb,dl,pd,st,raw,rem}
}
function logs(date){return(state.logs||[]).filter(x=>x.date===date)}function totals(date){return logs(date).reduce((a,x)=>({k:a.k+(+x.calories||0),p:a.p+(+x.protein||0),c:a.c+(+x.carbs||0),f:a.f+(+x.fat||0)}),{k:0,p:0,c:0,f:0})}
function renderAll(){renderToday();renderFoods();renderTargets();if($("progress").classList.contains("on"))charts()}
function renderToday(){
 $("date").value=state.selectedDate;$("dateText").textContent=dparse(state.selectedDate).toLocaleDateString("en-AU",{weekday:"long",day:"numeric",month:"long"});
 let t=target(),x=totals(state.selectedDate),a=[["Calories",x.k,t.cal,"kcal"],["Protein",x.p,t.pro,"g"],["Carbs",x.c,t.carb,"g"],["Fat",x.f,t.fat,"g"]];
 $("kpis").innerHTML=a.map(v=>`<div class="card kpi"><span>${v[0]}</span><b>${num(v[1],v[0]==="Calories"?0:1)} ${v[3]}</b><span>Target ${num(v[2],v[0]==="Calories"?0:1)}</span></div>`).join("");
 $("logs").innerHTML=logs(state.selectedDate).map(l=>`<div class="logrow"><div><b>${l.foodName}</b><div class="small">${num(l.qty,2)} × ${l.serving||"serve"} · ${num(l.calories)} kcal · ${num(l.protein,1)}P ${num(l.carbs,1)}C ${num(l.fat,1)}F</div></div><button class="btn alt" onclick="delLog('${l.id}')">Remove</button></div>`).join("")||'<div class="notice">Nothing logged yet.</div>';
 let w=state.weights?.[state.selectedDate]?.weight??"",ac=state.activities?.[state.selectedDate]||{};$("weight").value=w;$("steps").value=ac.steps||"";$("workout").value=ac.workout||"";$("mins").value=ac.minutes||"";
 $("summary").innerHTML=`<div class="foodrow"><span>Maintenance</span><b>${num(t.maint)} kcal</b></div><div class="foodrow"><span>Food</span><b>${num(x.k)} kcal</b></div><div class="foodrow"><span>Deficit before activity</span><b>${num(t.maint-x.k)} kcal</b></div>`;
 searchFoods()
}
function searchFoods(){let q=$("q").value.toLowerCase(),c=$("cat").value,list=state.foods.filter(f=>(!q||(`${f.name} ${f.serving}`).toLowerCase().includes(q))&&(!c||f.category===c)).slice(0,80);$("foods").innerHTML=list.map(f=>`<div class="foodrow"><div><b>${f.name}</b><div class="small">${f.serving} · ${num(f.calories)} kcal · ${num(f.protein,1)}P ${num(f.carbs,1)}C ${num(f.fat,1)}F</div></div><button class="btn" onclick="addFood('${f.id}')">Add</button></div>`).join("")}
window.addFood=id=>{let f=state.foods.find(x=>x.id===id),q=prompt(`Quantity of "${f.serving}"?`,"1");if(q===null)return;q=+q||1;state.logs.push({id:"l_"+Date.now()+Math.random(),date:state.selectedDate,foodId:f.id,foodName:f.name,serving:f.serving,qty:q,calories:f.calories*q,protein:f.protein*q,carbs:f.carbs*q,fat:f.fat*q,notes:""});save();renderToday()};
window.delLog=id=>{state.logs=state.logs.filter(x=>x.id!==id);save();renderToday()};
$("savecheck").onclick=()=>{let d=state.selectedDate,w=+$("weight").value;if(w)state.weights[d]={weight:w,note:""};else delete state.weights[d];state.activities=state.activities||{};state.activities[d]={steps:+$("steps").value||0,workout:$("workout").value,minutes:+$("mins").value||0};save();renderAll()};
function renderFoods(){let cats=[...new Set(state.foods.map(f=>f.category||"Other"))].sort();let cur=$("cat").value;$("cat").innerHTML='<option value="">All categories</option>'+cats.map(c=>`<option>${c}</option>`).join("");$("cat").value=cur;$("count").textContent=`${state.foods.length} foods`;let q=$("libq").value.toLowerCase();$("lib").innerHTML=state.foods.filter(f=>!q||(`${f.name} ${f.serving}`).toLowerCase().includes(q)).slice(0,180).map(f=>`<div class="foodrow"><div><b>${f.name}</b><div class="small">${f.serving} · ${f.category||""}</div></div><div class="macro">${num(f.calories)} kcal · ${num(f.protein,1)}P ${num(f.carbs,1)}C ${num(f.fat,1)}F</div></div>`).join("")}
$("showAdd").onclick=()=>$("addfood").classList.toggle("hidden");$("addf").onclick=()=>{let p=+$("fp").value||0,c=+$("fc").value||0,f=+$("ff").value||0,n=$("fn").value.trim();if(!n)return alert("Enter a food name.");let k=$("fk").value===""?p*4+c*4+f*9:+$("fk").value;state.foods.unshift({id:"f_"+Date.now(),name:n,serving:$("fs").value||"1 serve",calories:k,protein:p,carbs:c,fat:f,category:"Custom",source:"Custom"});["fn","fs","fp","fc","ff","fk"].forEach(i=>$(i).value="");save();renderAll()};
function renderTargets(){let t=target(),s=state.settings;$("gw").value=s.goalWeight;$("gd").value=s.goalDate;$("tstatus").innerHTML=`<div class="notice ${t.st.includes("AGGRESSIVE")?"warn":""}"><b>${t.st}</b><br>${t.rem} days · raw maths ${num(t.raw)} kcal · BMR floor ${num(t.bmr)} kcal</div>`;$("tvals").innerHTML=[["Current weight",num(t.w,1)+" kg"],["Maintenance",num(t.maint)+" kcal"],["Calories",num(t.cal)+" kcal"],["Protein",num(t.pro,1)+" g"],["Carbs",num(t.carb,1)+" g"],["Fat",num(t.fat,1)+" g"],["Weekly loss",num(t.dl*7,2)+" kg"],["Projected goal",t.pd]].map(x=>`<div class="foodrow"><span>${x[0]}</span><b>${x[1]}</b></div>`).join("")}
$("savetarget").onclick=()=>{state.settings.goalWeight=+$("gw").value||state.settings.goalWeight;state.settings.goalDate=$("gd").value||state.settings.goalDate;save();renderAll()};
function line(id,vals,target){let c=$(id),x=c.getContext("2d"),w=c.width=c.clientWidth*devicePixelRatio,h=c.height=c.clientHeight*devicePixelRatio;x.scale(devicePixelRatio,devicePixelRatio);w=c.clientWidth;h=c.clientHeight;x.clearRect(0,0,w,h);let all=vals.filter(Number.isFinite).concat(target||[]),mn=Math.min(...all,0),mx=Math.max(...all,1),px=i=>30+(w-45)*i/Math.max(1,vals.length-1),py=v=>15+(h-35)*(1-(v-mn)/(mx-mn||1));x.strokeStyle="#e5e7eb";for(let i=0;i<5;i++){let y=15+(h-35)*i/4;x.beginPath();x.moveTo(30,y);x.lineTo(w-10,y);x.stroke()}[[vals,"#2563eb"],[target,"#94a3b8"]].forEach(([a,col])=>{if(!a)return;x.strokeStyle=col;x.lineWidth=2;x.beginPath();a.forEach((v,i)=>{if(!Number.isFinite(v))return;i?x.lineTo(px(i),py(v)):x.moveTo(px(i),py(v))});x.stroke()})}
function charts(){let ds=[],w=[],cal=[];for(let i=29;i>=0;i--){let d=add(iso(),-i);ds.push(d);w.push(state.weights?.[d]?.weight??NaN);cal.push(totals(d).k||NaN)}let t=target();line("wc",w,ds.map((d,i)=>state.settings.startWeight+(state.settings.goalWeight-state.settings.startWeight)*Math.min(1,Math.max(0,days(state.settings.startDate,d)/Math.max(1,days(state.settings.startDate,state.settings.goalDate))))));line("cc",cal,ds.map(()=>t.cal))}
document.querySelectorAll(".tabs button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tabs button").forEach(x=>x.classList.toggle("on",x===b));document.querySelectorAll(".page").forEach(p=>p.classList.remove("on"));$(b.dataset.p==="foods"?"foodsPage":b.dataset.p).classList.add("on");if(b.dataset.p==="progress")setTimeout(charts,50)});
$("date").onchange=e=>{state.selectedDate=e.target.value;save();renderToday()};$("q").oninput=searchFoods;$("cat").onchange=searchFoods;$("libq").oninput=renderFoods;
boot();
