const BASE="https://jlmqnvyznyaoapjkyjmj.supabase.co";
const KEY="sb_publishable_gKNmo1rAdNZfg_BWGCehxQ_qfaoD3nj";
const SESSION_KEY="isaak_cut_tracker_session_v2";
const PERSONAL_FOODS=[{id:"f_20260821_waterfront_pantry_iced_latte_small",name:"Waterfront Pantry Iced Latte — Small",serving:"1 small",calories:150,protein:8,carbs:12,fat:8,category:"Custom",source:"Estimated cafe item — full cream milk, no syrup"},{id:"f_20260825_black_bowl_egg_noodles_chicken_beef_mixed_veg",name:"Egg Noodles with Chicken & Beef, Mixed Veg — Black Cereal Bowl",serving:"1 black cereal bowl",calories:610,protein:40,carbs:72,fat:17,category:"Custom",source:"Estimated homemade bowl"},{id:"f_20260825_barbell_meat_stick_bites_classic_70g",name:"Barbell Meat Stick Bites — Classic Spice 70 g",serving:"1 bag (70 g)",calories:286.4,protein:31.4,carbs:1.4,fat:17.6,category:"Custom",source:"Package nutrition label"},{id:"f_20260826_meatball_sub_photo",name:"Meatball Sub — Photo Estimate",serving:"1 whole sub",calories:800,protein:43,carbs:72,fat:37,category:"Custom",source:"Estimated from photo — meatballs/beef, tomato sauce, cheese and bread"},{id:"f_20260826_indomie_mi_goreng_85g",name:"Indomie Mi Goreng Fried Noodles — 85 g Packet",serving:"1 packet (85 g)",calories:376,protein:7.8,carbs:46.2,fat:16.2,category:"Custom",source:"Woolworths branded nutrition listing — 85 g calculated from per 100 g label"},{id:"f_20260826_continental_mushroom_bacon_soup_108",name:"Continental Mushroom & Bacon Soup — 108 kcal Sachet",serving:"1 sachet prepared (250 mL)",calories:108,protein:1.5,carbs:14.8,fat:4.0,category:"Custom",source:"User-confirmed 108 kcal; current Mushroom & Bacon retail-label macros"},{id:"f_20260827_chicken_mince_cooked_100g",name:"Chicken Mince — Cooked (100 g)",serving:"100 g",calories:170,protein:25,carbs:0,fat:7.5,category:"Custom",source:"Generic lean cooked chicken mince estimate"},{id:"f_20260827_pasta_cooked_100g",name:"Pasta — Cooked (100 g)",serving:"100 g",calories:158,protein:5.8,carbs:30.9,fat:0.9,category:"Custom",source:"Generic cooked pasta estimate"},{id:"f_20260828_cheeky_chicken_salad_roll_bbq",name:"Cheeky Chicken — Chicken Salad Roll with BBQ Sauce",serving:"1 whole roll",calories:680,protein:45,carbs:88,fat:16,category:"Custom",source:"Estimated from Cheeky Chicken menu ingredients — chicken breast, lettuce, tomato, carrot, long roll and BBQ sauce"},{id:"f_20260828_ij_salt_pepper_squid_piece_19g",name:"I&J Salt & Pepper Squid — 1 Piece (~19 g)",serving:"1 piece (~19 g)",calories:29,protein:2.0,carbs:2.6,fat:1.1,category:"Custom",source:"I&J retail nutrition per 100 g; per-piece weight estimated from current I&J foodservice spec (~4 pieces per 76 g)"}];
let session=null,user=null,state=null,timer=null,saving=false,pollTimer=null;
const $=x=>document.getElementById(x),num=(v,d=0)=>{v=+v||0;let p=10**d;return Math.round(v*p)/p},iso=()=>new Date().toISOString().slice(0,10);
const dparse=s=>new Date(s+"T00:00:00"),add=(s,n)=>{let d=dparse(s);d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)},days=(a,b)=>Math.round((dparse(b)-dparse(a))/86400000);
function status(t,c=""){let e=$("sync");e.textContent=t;e.className="pill "+c}
function msg(t,bad=false){$("amsg").textContent=t;$("amsg").className="notice "+(bad?"danger":"")}
function headers(auth=false,extra={}){let h={apikey:KEY,"Content-Type":"application/json",...extra};if(auth&&session?.access_token)h.Authorization="Bearer "+session.access_token;return h}
function storeSession(s){session=s;user=s?.user||null;if(s)localStorage.setItem(SESSION_KEY,JSON.stringify(s));else localStorage.removeItem(SESSION_KEY)}
async function jsonFetch(url,opts={},auth=false,retry=true){let r=await fetch(BASE+url,{...opts,headers:headers(auth,opts.headers||{})});if(r.status===401&&auth&&retry&&session?.refresh_token){let ok=await refreshSession();if(ok)return jsonFetch(url,opts,auth,false)}let text=await r.text(),data=null;try{data=text?JSON.parse(text):null}catch{data=text}if(!r.ok)throw new Error(data?.msg||data?.message||data?.error_description||data?.error||("Request failed ("+r.status+")"));return data}
let sessionRefreshTimer=null,refreshPromise=null;
function sessionExpiresSoon(bufferSec=1800){const exp=+session?.expires_at||0;return !exp||exp*1000-Date.now()<bufferSec*1000}
async function refreshSession(){
 if(refreshPromise)return refreshPromise;
 if(!session?.refresh_token)return false;
 refreshPromise=(async()=>{try{const previous=session;let d=await jsonFetch("/auth/v1/token?grant_type=refresh_token",{method:"POST",body:JSON.stringify({refresh_token:previous.refresh_token})},false,false);if(!d?.access_token)throw new Error("No refreshed access token returned");storeSession({...previous,...d,user:d.user||previous.user});return true}catch(e){console.warn("Session refresh deferred; keeping saved login",e);return false}finally{refreshPromise=null}})();
 return refreshPromise;
}
function startSessionKeepAlive(){clearInterval(sessionRefreshTimer);sessionRefreshTimer=setInterval(()=>{if(session?.refresh_token&&sessionExpiresSoon(1800))refreshSession()},15*60*1000)}
async function getUser(){if(!session?.access_token)return null;try{let d=await jsonFetch("/auth/v1/user",{method:"GET"},true);user=d;session.user=d;storeSession(session);return d}catch{return null}}
async function seed(){let data=await jsonFetch("/rest/v1/app_seed?select=content&order=part.asc",{method:"GET"},false);let b=(data||[]).map(x=>x.content).join("");if(!b)throw new Error("Starting food library could not be loaded.");if(typeof DecompressionStream==="undefined")throw new Error("This browser needs a newer Safari/Chrome version to load the food library.");let bin=Uint8Array.from(atob(b),c=>c.charCodeAt(0)),stream=new Blob([bin]).stream().pipeThrough(new DecompressionStream("gzip"));return JSON.parse(await new Response(stream).text())}
function hasPersonalFood(s,item){return(s?.foods||[]).some(f=>f.id===item.id||String(f.name||"").toLowerCase()===item.name.toLowerCase())}
function mergeSeed(s,base){let current=[...(s.foods||[])],have=new Set(current.map(f=>f.name));let foods=[...current,...(base.foods||[]).filter(f=>!have.has(f.name))];for(const item of PERSONAL_FOODS){if(!foods.some(f=>f.id===item.id||String(f.name||"").toLowerCase()===item.name.toLowerCase()))foods.unshift({...item})}return {...base,...s,foods}}
async function loadCloud(){status("Loading…");let base=await seed();let rows=await jsonFetch("/rest/v1/app_state?user_id=eq."+encodeURIComponent(user.id)+"&select=state",{method:"GET"},true);let needsPersonalSave=false;if(rows?.[0]?.state){needsPersonalSave=PERSONAL_FOODS.some(item=>!hasPersonalFood(rows[0].state,item));state=mergeSeed(rows[0].state,base)}else{state=mergeSeed(base,base);await jsonFetch("/rest/v1/app_state",{method:"POST",headers:{Prefer:"return=minimal"},body:JSON.stringify({user_id:user.id,state})},true)}if(needsPersonalSave){await jsonFetch("/rest/v1/app_state?user_id=eq."+encodeURIComponent(user.id),{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({state,updated_at:new Date().toISOString()})},true)}if(!state.selectedDate)state.selectedDate=iso();renderAll();$("auth").classList.add("hidden");$("signout").classList.remove("hidden");status("Live","live");startSessionKeepAlive();startPolling()}
async function pullCloud(){if(!user||saving)return;try{let rows=await jsonFetch("/rest/v1/app_state?user_id=eq."+encodeURIComponent(user.id)+"&select=state",{method:"GET"},true);if(rows?.[0]?.state){let base=await seed(),incoming=mergeSeed(rows[0].state,base);if(JSON.stringify(incoming)!==JSON.stringify(state)){state=incoming;renderAll();status("Updated","live");setTimeout(()=>status("Live","live"),700)}}}catch(e){status("Offline")}}
function startPolling(){clearInterval(pollTimer);pollTimer=setInterval(pullCloud,5000)}
function save(){if(!user||!state)return;clearTimeout(timer);status("Syncing…");timer=setTimeout(async()=>{saving=true;try{await jsonFetch("/rest/v1/app_state?user_id=eq."+encodeURIComponent(user.id),{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({state,updated_at:new Date().toISOString()})},true);status("Live","live")}catch(e){status("Sync error");console.error(e)}finally{saving=false}},250)}
async function boot(){try{let raw=localStorage.getItem(SESSION_KEY);if(raw){session=JSON.parse(raw);if(session?.refresh_token)await refreshSession();let u=await getUser();if(u){startSessionKeepAlive();await loadCloud();return}if(session?.refresh_token&&await refreshSession()){u=await getUser();if(u){startSessionKeepAlive();await loadCloud();return}}}}catch(e){console.error(e)}status("Sign in")}
$("signin").onclick=async()=>{let e=$("email").value.trim(),p=$("pass").value;if(!e||!p){msg("Enter your email and password.",true);return}msg("Signing in…");try{let d=await jsonFetch("/auth/v1/token?grant_type=password",{method:"POST",body:JSON.stringify({email:e,password:p})},false);storeSession(d);await loadCloud();msg("Signed in.")}catch(err){msg(err.message,true)}};
$("signup").onclick=async()=>{let e=$("email").value.trim(),p=$("pass").value;if(!e||p.length<6){msg("Use a valid email and password of at least 6 characters.",true);return}msg("Creating account…");try{let d=await jsonFetch("/auth/v1/signup",{method:"POST",body:JSON.stringify({email:e,password:p})},false);if(d?.access_token){storeSession(d);await loadCloud();msg("Account created.")}else msg("Account created. Check your email to confirm it, then come back here and sign in.")}catch(err){msg(err.message,true)}};
$("signout").onclick=async()=>{try{if(session?.access_token)await jsonFetch("/auth/v1/logout",{method:"POST"},true)}catch{}clearInterval(pollTimer);clearInterval(sessionRefreshTimer);storeSession(null);state=null;$("auth").classList.remove("hidden");$("signout").classList.add("hidden");status("Signed out");msg("Signed out. Use the same login on your other device.")};
window.addEventListener("focus",async()=>{if(session?.refresh_token&&sessionExpiresSoon(3600))await refreshSession();if(user)pullCloud()});
document.addEventListener("visibilitychange",()=>{if(document.visibilityState==="visible"&&session?.refresh_token&&sessionExpiresSoon(3600))refreshSession()});
window.addEventListener("online",async()=>{if(session?.refresh_token){const ok=await refreshSession();if(ok&&!user)boot()}});
function weight(date=iso()){let a=Object.entries(state.weights||{}).filter(([d,v])=>d<=date&&v?.weight).sort();return a.length?+a[a.length-1][1].weight:+state.settings.startWeight}
function target(){let s=state.settings,w=weight(),bf=Math.max(0,Math.min(.7,+s.bodyFat||.22)),lean=w*(1-bf),k=370+21.6*lean,m=s.sex==="Female"?10*w+6.25*s.heightCm-5*s.age-161:10*w+6.25*s.heightCm-5*s.age+5,bmr=(k+m)/2;let maint=s.manualMaintenance?+s.manualMaintenance:s.maintenanceAtStart*Math.pow(w/s.startWeight,.75),rem=Math.max(0,days(iso(),s.goalDate)),lose=Math.max(0,w-s.goalWeight),raw=rem?maint-lose*7700/rem:maint,cal=Math.max(bmr,raw),def=Math.max(0,maint-cal),pro=w*2.2*.9,fat=w*2.2*.4,carb=Math.max(0,(cal-pro*4-fat*9)/4),dl=def/7700,pd=dl&&lose?add(iso(),Math.ceil(lose/dl)):s.goalDate;let st=w<=s.goalWeight?"GOAL REACHED":rem<=0?"CHOOSE A FUTURE DATE":raw<bmr?"DATE TOO AGGRESSIVE — BMR FLOOR USED":"ON TRACK FOR SELECTED DATE";return{w,bmr,maint,cal,def,pro,fat,carb,dl,pd,st,raw,rem}}
function logs(date){return(state.logs||[]).filter(x=>x.date===date)}function totals(date){return logs(date).reduce((a,x)=>({k:a.k+(+x.calories||0),p:a.p+(+x.protein||0),c:a.c+(+x.carbs||0),f:a.f+(+x.fat||0)}),{k:0,p:0,c:0,f:0})}
function renderAll(){renderToday();renderFoods();renderTargets();if($("progress").classList.contains("on"))charts()}
function renderToday(){$("date").value=state.selectedDate;$("dateText").textContent=dparse(state.selectedDate).toLocaleDateString("en-AU",{weekday:"long",day:"numeric",month:"long"});let t=target(),x=totals(state.selectedDate),a=[["Calories",x.k,t.cal,"kcal"],["Protein",x.p,t.pro,"g"],["Carbs",x.c,t.carb,"g"],["Fat",x.f,t.fat,"g"]];$("kpis").innerHTML=a.map(v=>`<div class="card kpi"><span>${v[0]}</span><b>${num(v[1],v[0]==="Calories"?0:1)} ${v[3]}</b><span>Target ${num(v[2],v[0]==="Calories"?0:1)}</span></div>`).join("");$("logs").innerHTML=logs(state.selectedDate).map(l=>`<div class="logrow"><div><b>${l.foodName}</b><div class="small">${num(l.qty,2)} × ${l.serving||"serve"} · ${num(l.calories)} kcal · ${num(l.protein,1)}P ${num(l.carbs,1)}C ${num(l.fat,1)}F</div></div><button class="btn alt" onclick="delLog('${l.id}')">Remove</button></div>`).join("")||'<div class="notice">Nothing logged yet.</div>';let w=state.weights?.[state.selectedDate]?.weight??"",ac=state.activities?.[state.selectedDate]||{};$("weight").value=w;$("steps").value=ac.steps||"";$("workout").value=ac.workout||"";$("mins").value=ac.minutes||"";$("summary").innerHTML=`<div class="foodrow"><span>Maintenance</span><b>${num(t.maint)} kcal</b></div><div class="foodrow"><span>Food</span><b>${num(x.k)} kcal</b></div><div class="foodrow"><span>Deficit before activity</span><b>${num(t.maint-x.k)} kcal</b></div>`;searchFoods()}
function searchFoods(){let q=$("q").value.toLowerCase(),c=$("cat").value,list=state.foods.filter(f=>(!q||(`${f.name} ${f.serving}`).toLowerCase().includes(q))&&(!c||f.category===c)).slice(0,80);$("foods").innerHTML=list.map(f=>`<div class="foodrow"><div><b>${f.name}</b><div class="small">${f.serving} · ${num(f.calories)} kcal · ${num(f.protein,1)}P ${num(f.carbs,1)}C ${num(f.fat,1)}F</div></div><button class="btn" onclick="addFood('${f.id}')">Add</button></div>`).join("")}
window.addFood=id=>{let f=state.foods.find(x=>x.id===id),q=prompt(`Quantity of "${f.serving}"?`,"1");if(q===null)return;q=+q||1;state.logs.push({id:"l_"+Date.now()+Math.random(),date:state.selectedDate,foodId:f.id,foodName:f.name,serving:f.serving,qty:q,calories:f.calories*q,protein:f.protein*q,carbs:f.carbs*q,fat:f.fat*q,notes:""});save();renderToday()};
window.delLog=id=>{state.logs=state.logs.filter(x=>x.id!==id);save();renderToday()};
$("savecheck").onclick=()=>{let d=state.selectedDate,w=+$("weight").value;if(w)state.weights[d]={weight:w,note:""};else delete state.weights[d];state.activities=state.activities||{};state.activities[d]={steps:+$("steps").value||0,workout:$("workout").value,minutes:+$("mins").value||0};save();renderAll()};
function renderFoods(){let cats=[...new Set(state.foods.map(f=>f.category||"Other"))].sort(),cur=$("cat").value;$("cat").innerHTML='<option value="">All categories</option>'+cats.map(c=>`<option>${c}</option>`).join("");$("cat").value=cur;$("count").textContent=`${state.foods.length} foods`;let q=$("libq").value.toLowerCase();$("lib").innerHTML=state.foods.filter(f=>!q||(`${f.name} ${f.serving}`).toLowerCase().includes(q)).slice(0,180).map(f=>`<div class="foodrow"><div><b>${f.name}</b><div class="small">${f.serving} · ${f.category||""}</div></div><div class="macro">${num(f.calories)} kcal · ${num(f.protein,1)}P ${num(f.carbs,1)}C ${num(f.fat,1)}F</div></div>`).join("")}
$("showAdd").onclick=()=>$("addfood").classList.toggle("hidden");$("addf").onclick=()=>{let p=+$("fp").value||0,c=+$("fc").value||0,f=+$("ff").value||0,n=$("fn").value.trim();if(!n)return alert("Enter a food name.");let k=$("fk").value===""?p*4+c*4+f*9:+$("fk").value;state.foods.unshift({id:"f_"+Date.now(),name:n,serving:$("fs").value||"1 serve",calories:k,protein:p,carbs:c,fat:f,category:"Custom",source:"Custom"});["fn","fs","fp","fc","ff","fk"].forEach(i=>$(i).value="");save();renderAll()};
function renderTargets(){let t=target(),s=state.settings;$("gw").value=s.goalWeight;$("gd").value=s.goalDate;$("tstatus").innerHTML=`<div class="notice ${t.st.includes("AGGRESSIVE")?"warn":""}"><b>${t.st}</b><br>${t.rem} days · raw maths ${num(t.raw)} kcal · BMR floor ${num(t.bmr)} kcal</div>`;$("tvals").innerHTML=[["Current weight",num(t.w,1)+" kg"],["Maintenance",num(t.maint)+" kcal"],["Calories",num(t.cal)+" kcal"],["Protein",num(t.pro,1)+" g"],["Carbs",num(t.carb,1)+" g"],["Fat",num(t.fat,1)+" g"],["Weekly loss",num(t.dl*7,2)+" kg"],["Projected goal",t.pd]].map(x=>`<div class="foodrow"><span>${x[0]}</span><b>${x[1]}</b></div>`).join("")}
$("savetarget").onclick=()=>{state.settings.goalWeight=+$("gw").value||state.settings.goalWeight;state.settings.goalDate=$("gd").value||state.settings.goalDate;save();renderAll()};
function line(id,vals,target){let c=$(id),x=c.getContext("2d"),w=c.width=c.clientWidth*devicePixelRatio,h=c.height=c.clientHeight*devicePixelRatio;x.scale(devicePixelRatio,devicePixelRatio);w=c.clientWidth;h=c.clientHeight;x.clearRect(0,0,w,h);let all=vals.filter(Number.isFinite).concat(target||[]),mn=Math.min(...all,0),mx=Math.max(...all,1),px=i=>30+(w-45)*i/Math.max(1,vals.length-1),py=v=>15+(h-35)*(1-(v-mn)/(mx-mn||1));x.strokeStyle="#e5e7eb";for(let i=0;i<5;i++){let y=15+(h-35)*i/4;x.beginPath();x.moveTo(30,y);x.lineTo(w-10,y);x.stroke()}[[vals,"#2563eb"],[target,"#94a3b8"]].forEach(([a,col])=>{if(!a)return;x.strokeStyle=col;x.lineWidth=2;x.beginPath();a.forEach((v,i)=>{if(!Number.isFinite(v))return;i?x.lineTo(px(i),py(v)):x.moveTo(px(i),py(v))});x.stroke()})}
function charts(){let ds=[],w=[],cal=[];for(let i=29;i>=0;i--){let d=add(iso(),-i);ds.push(d);w.push(state.weights?.[d]?.weight??NaN);cal.push(totals(d).k||NaN)}let t=target();line("wc",w,ds.map(d=>state.settings.startWeight+(state.settings.goalWeight-state.settings.startWeight)*Math.min(1,Math.max(0,days(state.settings.startDate,d)/Math.max(1,days(state.settings.startDate,state.settings.goalDate))))));line("cc",cal,ds.map(()=>t.cal))}
document.querySelectorAll(".tabs button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tabs button").forEach(x=>x.classList.toggle("on",x===b));document.querySelectorAll(".page").forEach(p=>p.classList.remove("on"));$(b.dataset.p==="foods"?"foodsPage":b.dataset.p).classList.add("on");if(b.dataset.p==="progress")setTimeout(charts,50)});
$("date").onchange=e=>{state.selectedDate=e.target.value;save();renderToday()};$("q").oninput=searchFoods;$("cat").onchange=searchFoods;$("libq").oninput=renderFoods;
boot();
setTimeout(()=>{const s=document.createElement("script");s.src="./work-addon.js?v=1";document.body.appendChild(s)},0);
