/* Work shift tracking addon. */
setTimeout(function installWorkTracking(){
  try{
    const saveBtn=$('savecheck');
    if(!saveBtn || $('workShift')) return;

    const WORK_GROUPS={
      'Office & Professional':[['Accountant',1.4],['Architect',1.5],['Bank teller',1.8],['Bookkeeper',1.4],['Call centre worker',1.4],['Data analyst',1.3],['Engineer — office based',1.4],['Graphic designer',1.3],['IT / software developer',1.3],['Lawyer / solicitor',1.4],['Manager — office based',1.4],['Receptionist',1.5],['Sales representative — office',1.5],['Student / study day',1.3],['Surveyor — office based',1.4],['Quantity surveyor — office based',1.4],['Real estate agent — office/admin',1.6]],
      'Retail & Hospitality':[['Barista',2.5],['Bartender',2.6],['Bottle shop worker',2.3],['Cafe worker',2.6],['Cashier',1.8],['Chef',2.8],['Cook / kitchen hand',3.0],['Fast food worker',2.6],['Front desk / hotel reception',1.8],['Grocery worker',2.5],['Hotel worker — general duties',2.5],['Retail assistant',2.2],['Restaurant server / waiter',2.8],['Shelf stacker',3.0],['Supermarket deli worker',2.3],['Supermarket night fill',3.2],['Venue / event staff',2.7]],
      'Healthcare & Care':[['Aged care worker',3.0],['Ambulance paramedic',3.5],['Carer / disability support worker',2.8],['Dental assistant',2.0],['Dentist',1.8],['Doctor — clinic',1.8],['Doctor — hospital rounds',2.3],['Nurse — ward',3.0],['Nurse — theatre / procedure',2.3],['Occupational therapist',2.2],['Orderly / patient transport',3.0],['Pharmacist',2.0],['Physiotherapist',2.5],['Veterinarian',2.5],['Veterinary nurse',2.8]],
      'Trades & Construction':[['Bricklayer',4.5],['Builder / construction worker',4.0],['Carpenter',3.5],['Concreter',4.5],['Construction labourer',4.5],['Electrician',3.0],['Floor layer',3.5],['Glazier',3.2],['HVAC / refrigeration technician',3.2],['Landscaper',4.0],['Mechanic',3.0],['Painter',3.0],['Plasterer',3.5],['Plumber',3.2],['Roofer',4.5],['Scaffolder',5.0],['Tiler',3.5],['Welder / boilermaker',3.3],['Window installer',3.5]],
      'Warehouse, Manufacturing & Industrial':[['Assembly line worker',2.5],['Factory worker — light duties',2.3],['Factory worker — heavy duties',3.8],['Forklift driver',2.0],['Machine operator',2.3],['Manufacturing technician',2.5],['Meat processing worker',3.2],['Picker / packer',3.2],['Storeperson',3.0],['Warehouse worker',3.2],['Warehouse loader / unloader',4.0]],
      'Transport & Delivery':[['Bus driver',1.5],['Courier',2.5],['Delivery driver',2.0],['Food delivery — bicycle',5.0],['Food delivery — car',1.8],['Removalist',4.5],['Taxi / rideshare driver',1.5],['Train driver',1.5],['Truck driver',1.5],['Truck driver — loading/unloading',2.8]],
      'Cleaning, Maintenance & Property':[['Cleaner — general',3.3],['Cleaner — heavy / commercial',4.0],['Gardener',3.5],['Groundskeeper',3.5],['Handyman',3.0],['Housekeeper',3.0],['Maintenance worker',3.0],['Pool cleaner',3.0],['Window cleaner',3.5]],
      'Outdoor, Agriculture & Animals':[['Arborist',4.5],['Farm worker — general',4.0],['Farm worker — heavy manual',5.0],['Fisher / commercial fishing',4.0],['Forestry worker',4.5],['Fruit picker',4.0],['Horse stable worker',3.5],['Lawn mowing / grounds work',4.0],['Nursery / garden centre worker',3.0],['Shearer',5.5],['Stock / livestock worker',4.0]],
      'Education & Childcare':[['Childcare educator',2.8],['Early childhood teacher',2.5],['Primary school teacher',2.2],['Secondary school teacher',2.0],['Teacher aide',2.2],['University lecturer',1.6]],
      'Emergency, Defence & Security':[['Corrections officer',2.3],['Firefighter — station / standby',2.0],['Firefighter — active incident',6.0],['Police officer — patrol',2.5],['Security guard — seated',1.5],['Security guard — standing/patrol',2.3],['Soldier / defence — light duties',2.5],['Soldier / defence — field duties',5.0]],
      'Personal, Beauty & Service':[['Barber',2.0],['Beauty therapist',1.8],['Dog groomer',2.5],['Hairdresser',2.0],['Massage therapist',2.2],['Personal shopper',2.5],['Tattoo artist',1.6]],
      'Sport, Recreation & Entertainment':[['Actor / performer',2.0],['Coach — mostly standing',2.5],['Fitness instructor',4.5],['Gym / recreation centre staff',2.2],['Lifeguard — normal duty',2.0],['Photographer — event',2.3],['Professional athlete — training shift',6.0],['Stage / road crew',3.5]],
      'Other / Mixed':[['Mixed duties — mostly sitting',1.5],['Mixed duties — mostly standing',2.0],['Mixed duties — walking/light manual',2.8],['Mixed duties — moderate manual',3.5],['Mixed duties — heavy manual',4.5],['Other / custom work',2.5]]
    };
    const jobs=[];Object.entries(WORK_GROUPS).forEach(([group,list])=>list.forEach(([name,met])=>jobs.push({group,name,met})));
    const level=met=>met<1.7?'Very light':met<2.4?'Light':met<3.3?'Moderate':met<4.5?'Hard':'Very hard';
    const jobMap=new Map(jobs.map(j=>[j.name,j]));
    const opts=Object.entries(WORK_GROUPS).map(([group,list])=>`<optgroup label="${group}">${list.map(([name,met])=>`<option value="${name}">${name} — ${level(met)}</option>`).join('')}</optgroup>`).join('');

    saveBtn.insertAdjacentHTML('beforebegin',`<div id="workSection" style="margin-top:14px;padding-top:12px;border-top:1px solid #eef2f7"><div class="row between" style="align-items:center"><div><b>Work shift</b><div class="small">Estimate work activity for this day</div></div><label style="margin:0;display:flex;gap:7px;align-items:center;font-size:13px;color:#101828"><input id="workShift" type="checkbox"> Worked today</label></div><div id="workFields" style="margin-top:8px"><label>Job / work type</label><select id="workJob" class="input"><option value="">Choose a job</option>${opts}</select><div id="workJobInfo" class="small" style="margin-top:5px"></div><div class="grid g2"><div><label>How hard was this shift?</label><select id="workIntensity" class="input"><option value="Easy">Easy for this job</option><option value="Typical" selected>Typical / normal</option><option value="Hard">Hard</option><option value="Very hard">Very hard</option></select></div><div><label>Shift hours</label><input id="workHours" class="input" type="number" min="0" max="24" step="0.25" placeholder="e.g. 8"></div></div><label style="display:flex;gap:7px;align-items:flex-start;font-size:12px;color:#475467;margin-top:9px"><input id="workStepsOverlap" type="checkbox" checked style="margin-top:2px"> Most of my recorded steps happened during work (prevents double-counting those steps with the work estimate)</label><div id="workEstimateNow" class="notice" style="margin-top:8px">Tick Worked today, choose your role and enter hours to estimate work calories.</div></div></div>`);

    const currentJob=()=>jobMap.get($('workJob')?.value)||null;
    const workMultiplier=x=>({'Easy':.85,'Typical':1,'Hard':1.15,'Very hard':1.3})[x]||1;
    function estimateWork(date){const a=state?.activities?.[date]||{};if(!a.workShift||!(+a.workHours>0))return{active:false,low:0,high:0,mid:0,met:0,hours:0,job:a.workJob||'',intensity:a.workIntensity||'Typical',overlap:a.workStepsOverlap!==false};const j=jobMap.get(a.workJob)||{name:a.workJob||'Other / custom work',met:2.5};const hours=Math.min(24,Math.max(0,+a.workHours||0)),met=Math.min(8.5,Math.max(1.2,j.met*workMultiplier(a.workIntensity||'Typical'))),w=weight(date),mins=hours*60,gross=met*3.5*w/200*mins,rest=3.5*w/200*mins,mid=Math.max(0,gross-rest);return{active:true,low:mid*.85,high:mid*1.15,mid,met,hours,job:j.name,intensity:a.workIntensity||'Typical',overlap:a.workStepsOverlap!==false,defaultLevel:level(j.met)}}
    window.workEstimate=estimateWork;
    function updateWorkInfo(){const j=currentJob();$('workJobInfo').textContent=j?`Default job intensity: ${level(j.met)} (~${j.met.toFixed(1)} MET). Use the shift intensity selector to adjust for how hard that day actually felt.`:'Choose the closest role; use Other / custom work if nothing fits.';if(!state||!$('workShift').checked){$('workEstimateNow').textContent='Tick Worked today, choose your role and enter hours to estimate work calories.';return}const d=state.selectedDate||melToday(),temp={...(state.activities?.[d]||{}),workShift:true,workJob:$('workJob').value,workIntensity:$('workIntensity').value,workHours:+$('workHours').value||0,workStepsOverlap:$('workStepsOverlap').checked},old=state.activities?.[d];state.activities=state.activities||{};state.activities[d]=temp;const e=estimateWork(d);if(old===undefined)delete state.activities[d];else state.activities[d]=old;$('workEstimateNow').innerHTML=e.active?`Estimated work activity above resting level: <b>${num(e.low)}–${num(e.high)} kcal</b> for ${num(e.hours,2)} h. This is an estimate, not an automatic amount to eat back.`:'Enter your shift hours to see the estimate.'}
    function toggleWorkFields(){const on=$('workShift').checked;['workJob','workIntensity','workHours','workStepsOverlap'].forEach(id=>$(id).disabled=!on);$('workFields').style.opacity=on?'1':'.55';updateWorkInfo()}
    ['workJob','workIntensity','workHours','workStepsOverlap'].forEach(id=>$(id).addEventListener('change',updateWorkInfo));$('workHours').addEventListener('input',updateWorkInfo);$('workShift').addEventListener('change',toggleWorkFields);

    const baseActivityEstimate=activityEstimate;
    activityEstimate=function(date){const a=baseActivityEstimate(date),wk=estimateWork(date),ac=state.activities?.[date]||{};let moveLow=a.stepLow,moveHigh=a.stepHigh;if(wk.active){if(ac.workStepsOverlap!==false){moveLow=Math.max(a.stepLow,wk.low);moveHigh=Math.max(a.stepHigh,wk.high)}else{moveLow=a.stepLow+wk.low;moveHigh=a.stepHigh+wk.high}}return{...a,workLow:wk.low,workHigh:wk.high,workMid:wk.mid,workMet:wk.met,workHours:wk.hours,workJob:wk.job,workIntensity:wk.intensity,workActive:wk.active,workOverlap:wk.overlap,totalLow:moveLow+a.workoutLow,totalHigh:moveHigh+a.workoutHigh}};

    const baseRenderToday=renderToday;
    renderToday=function(){baseRenderToday();const d=state.selectedDate||melToday(),ac=state.activities?.[d]||{};$('workShift').checked=!!ac.workShift;$('workJob').value=ac.workJob||'';$('workIntensity').value=ac.workIntensity||'Typical';$('workHours').value=ac.workHours||'';$('workStepsOverlap').checked=ac.workStepsOverlap!==false;toggleWorkFields();const e=activityEstimate(d),bits=[];if(e.steps)bits.push(`Steps ${num(e.stepLow)}–${num(e.stepHigh)} kcal`);if(e.workActive)bits.push(`Work ${num(e.workLow)}–${num(e.workHigh)} kcal`);if(e.workoutLow>0)bits.push(`Workout ${num(e.workoutLow)}–${num(e.workoutHigh)} kcal`);$('activityNow').innerHTML=bits.length?`Estimated activity burn: <b>${num(e.totalLow)}–${num(e.totalHigh)} kcal</b><br><span class="small">${bits.join(' · ')}${e.workActive&&e.workOverlap?' · work/steps overlap protected':''}</span>`:'Enter steps, a workout and/or a work shift to see an estimated calorie-burn range.'};

    const baseRenderProgressExtras=renderProgressExtras;
    renderProgressExtras=function(){baseRenderProgressExtras();const d=state.selectedDate||melToday(),e=activityEstimate(d),box=$('activityProgress');if(!box)return;box.insertAdjacentHTML('beforeend',`<div class="spacer8"></div><div class="stat"><span>Work shift</span><b>${e.workActive?`${num(e.workLow)}–${num(e.workHigh)} kcal`:'No shift entered'}</b><div class="small">${e.workActive?`${e.workJob} · ${num(e.workHours,2)} h · ${e.workIntensity} shift · ~${num(e.workMet,1)} MET${e.workOverlap?' · work/step overlap protected':''}`:'Tick Worked today in Check-in, choose a job and enter hours.'}</div></div>`)};

    $('savecheck').onclick=()=>{const d=state.selectedDate||melToday(),w=+$('weight').value;if(w)state.weights[d]={weight:w,note:''};else delete state.weights[d];state.activities=state.activities||{};state.activities[d]={steps:+$('steps').value||0,workout:$('workout').value,minutes:+$('mins').value||0,intensity:$('intensity').value||'Moderate',workShift:$('workShift').checked,workJob:$('workJob').value,workIntensity:$('workIntensity').value||'Typical',workHours:+$('workHours').value||0,workStepsOverlap:$('workStepsOverlap').checked};save();renderAll();const m=$('checkmsg'),e=activityEstimate(d);m.textContent=`Check-in saved. Targets recalculated from ${num(weight(melToday()),1)} kg${e.workActive?` · work estimate ${num(e.workLow)}–${num(e.workHigh)} kcal`:''} and syncing.`;m.classList.remove('hidden');clearTimeout(window.__checkMsgTimer);window.__checkMsgTimer=setTimeout(()=>m.classList.add('hidden'),3200)};

    if(state)renderAll();else toggleWorkFields();
  }catch(e){console.error('Work tracking addon failed',e)}
},0);
